[package]
name = "bsfun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
# plotters is only used for the example plots
plotters = "0.3.4"